/* Copyright © 2026 Zenin Easa Panthakkalakath */

// Regenerates packaging/linux/com.konjugate.Konjugate.metainfo.xml from packaging/appMetadata.yml
// (the shared descriptive text) plus package.json's current version -- see appMetadata.yml's own
// comment for why this exists: the same descriptive text was previously hand-copied separately into
// this file and distribution/snap/snapcraft.yaml, and had already drifted by one punctuation mark.
//
// The version/date this writes are still only a last-known-good snapshot, same as before -- the
// Makefile's distributableLinux target unconditionally overwrites both with the live version at
// actual AppImage build time regardless of what's committed here (see its own comment). Baking a
// real, current version in here too matters for a different reason: Flathub's x-checker-data
// mechanism (see docs/packageManagerDistribution.md) reads this committed file directly, not
// anything the Makefile produces, to detect new releases.
//
// Usage: npm run generate:app-metainfo

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { load } from 'js-yaml';

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = join(projectRoot, 'packaging', 'linux', 'com.konjugate.Konjugate.metainfo.xml');

const metadata = load(await readFile(join(projectRoot, 'packaging', 'appMetadata.yml'), 'utf8'));
const { version } = JSON.parse(await readFile(join(projectRoot, 'package.json'), 'utf8'));

// Reuses the existing committed release date when the version hasn't actually changed, rather than
// always stamping today -- otherwise this script produces different output on every single day
// even when nothing real changed, which would make a "regenerate and diff" CI check (see
// crossPlatform.yml) fail constantly on pure date churn instead of on an actual drift.
const existingRelease = /<release version="([^"]*)" date="([^"]*)" \/>/.exec(await readFile(outputPath, 'utf8').catch(() => ''));
const date = existingRelease?.[1] === version ? existingRelease[2] : new Date().toISOString().slice(0, 10);

const escapeXml = (text) => String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const paragraphs = metadata.description.map((paragraph) => `    <p>\n      ${escapeXml(paragraph)}\n    </p>`).join('\n');
const categories = metadata.categories.map((category) => `    <category>${escapeXml(category)}</category>`).join('\n');
const screenshotUrl = `https://raw.githubusercontent.com/zenineasa/Konjugate/v${version}/${metadata.screenshot.path}`;

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright © 2026 Zenin Easa Panthakkalakath -->
<!-- Generated by scripts/generateAppMetainfo.mjs from packaging/appMetadata.yml. Edit that file
     and re-run \`npm run generate:app-metainfo\` rather than editing this one directly. -->
<component type="desktop-application">
  <id>${escapeXml(metadata.appId)}</id>
  <name>${escapeXml(metadata.name)}</name>
  <summary>${escapeXml(metadata.summary)}</summary>
  <metadata_license>${escapeXml(metadata.metadataLicense)}</metadata_license>
  <project_license>${escapeXml(metadata.license)}</project_license>
  <developer id="${escapeXml(metadata.developerId)}">
    <name>${escapeXml(metadata.developerName)}</name>
  </developer>
  <url type="homepage">${escapeXml(metadata.homepage)}</url>
  <url type="bugtracker">${escapeXml(metadata.bugtracker)}</url>
  <launchable type="desktop-id">${escapeXml(metadata.appId)}.desktop</launchable>

  <description>
${paragraphs}
  </description>

  <screenshots>
    <screenshot type="default">
      <caption>${escapeXml(metadata.screenshot.caption)}</caption>
      <image>${escapeXml(screenshotUrl)}</image>
    </screenshot>
  </screenshots>

  <categories>
${categories}
  </categories>

  <content_rating type="oars-1.1" />

  <!-- Both this entry and the screenshot URL's version tag above are overwritten at AppImage build
       time (Makefile's distributableLinux target) with whatever package.json's version actually
       is. What's committed here is only ever a last-known-good snapshot for readability, not a
       value anything depends on staying in sync by hand. -->
  <releases>
    <release version="${version}" date="${date}" />
  </releases>
</component>
`;

await writeFile(outputPath, xml);
console.log(`Wrote ${outputPath}`);
